# Generated by Django 3.0.2 on 2020-02-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('product_code', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
