# Generated by Django 3.0.2 on 2020-02-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
