# Generated by Django 3.0.2 on 2020-02-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='favorite_code',
            new_name='product',
        ),
    ]
