# Generated by Django 3.0.2 on 2020-02-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_nutriscore', models.CharField(max_length=3)),
                ('product_image_url', models.URLField()),
                ('product_url', models.URLField()),
                ('product_energy_kj_100g', models.CharField(max_length=20)),
                ('product_fat_100g', models.CharField(max_length=20)),
                ('product_saturated_fat_100g', models.CharField(max_length=20)),
                ('product_salt_100g', models.CharField(max_length=20)),
                ('product_carbohydrates_100g', models.CharField(max_length=20)),
                ('product_fibers_100g', models.CharField(max_length=20)),
                ('product_sugars_100g', models.CharField(max_length=20)),
                ('product_proteins_100g', models.CharField(max_length=20)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
            ],
        ),
    ]
