# Generated by Django 3.0.2 on 2020-02-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdata',
        ),
    ]
