# Generated by Django 3.0.2 on 2020-02-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_energy_kcal_100g',
            new_name='product_energy_kj_100g',
        ),
    ]
